### ISSUE TITLE
Invalid slug

### ISSUE THREAD

**Issue by trzcina** [flotiq/wordpress-2-flotiq-sync#10]
After synchronization, I get this slug in my Flotiq
![image](https://user-images.githubusercontent.com/645716/115527974-e1f7c080-a291-11eb-98e3-a7f827316e59.png)

i think it should be "jak-udekorowac-mieszkanie-na-swieta-wielkanocne" like in my settings:
![image](https://user-images.githubusercontent.com/645716/115528500-60ecf900-a292-11eb-8e2e-9b2e18250794.png)

Wordpress v5.7

**Comment by mccdwv** [comment]
Cannot reproduce; looks like already solved

**Comment by trzcina** [comment]
Cannot reproduce; looks like already solved
