### ISSUE TITLE
Fatal error if uploaded file doesn't exists

### ISSUE THREAD

**Issue by trzcina** [flotiq/wordpress-2-flotiq-sync#3]
After click "Run synchronization" I have this error.
That's true, that this file is missing in the uploads directory, but it should not destroy the whole process.
![WordPress-›-Błąd](https://user-images.githubusercontent.com/645716/114159311-f220af00-9925-11eb-84dc-4e7c8924b1a4.png)

**Comment by KarolNet** [comment]
Fixed

**Comment by trzcina** [comment]
Thank you, everything is working fine now.
